development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: rub32912289
  host: 127.0.0.1
  database: appcupom_development

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: rub32912289
  host: 127.0.0.1
  database: appcupom_test

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root
  password: rub32912289
  host: localhost
  database: appcupom
